<a href="https://colab.research.google.com/github/RutujaBidkar/Certifications/blob/main/Numpy_DataType.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.vstack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.stack((a, b))

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr = np.arange(1, 10)

np.split(arr, 3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
np.hsplit(arr,3)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([10, 20, 30])

a + b

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
arr = np.array([40, 10, 30, 20])

np.sort(arr)

array([10, 20, 30, 40])

In [ ]:
np.argsort(arr)

array([1, 3, 2, 0])

In [ ]:
np.argmax(arr)

np.int64(0)

In [ ]:
np.argmin(arr)

np.int64(1)

In [ ]:
arr = np.array([10, 20, np.nan, 40])
np.isnan(arr)

array([False, False,  True, False])

In [ ]:
np.mean(arr)

np.float64(nan)

In [ ]:
arr = np.array([10, 20, 20, 30, 30, 30])
np.unique(arr)

array([10, 20, 30])

In [ ]:
np.unique(arr, return_counts=True)

(array([10, 20, 30]), array([1, 2, 3]))