<a href="https://colab.research.google.com/github/RutujaBidkar/Certifications/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np


In [ ]:
arr = np.array([1,2,3])

In [ ]:
#dimensions and shape of an array
arr.ndim

1

In [ ]:
arr = np.array(34)
arr.ndim

0

In [ ]:
a = np.array([[[[]]]])
a.ndim
a.shape

(1, 1, 1, 0)

In [ ]:
range = np.arange(1,10, 2)  #start, stop , step

In [ ]:
range

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
arr = np.linspace(0,1,10) #start stop, number of values
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [ ]:
arr = np.logspace(1,3,2)    #logirithmic sacle array -> 10^1 -> 10^3 ...3points
arr

array([  10., 1000.])

In [ ]:
#np.Zeros -> array full of zeros
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [ ]:
arr= np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.ones([4,2], dtype= int)
arr


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [ ]:
arr = np.full(10,2)    #create an array full of any value
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
arr = np.full([2,4],7.1)
arr

array([[7.1, 7.1, 7.1, 7.1],
       [7.1, 7.1, 7.1, 7.1]])

In [ ]:
arr = np.empty([2,3]) #uninsitalizated array ->create an array without setting any values
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr = np.random.rand(10)
arr

array([0.79156713, 0.46220259, 0.05413551, 0.89685133, 0.48598397,
       0.04762336, 0.03851549, 0.05782836, 0.18155016, 0.64582578])

In [ ]:
arr = np.random.rand(2,3)   #-> random floats from standard normal distribution
arr

array([[0.64882474, 0.00670896, 0.74545945],
       [0.46072777, 0.58661947, 0.14305127]])

In [ ]:
arr = np.random.randint(10,100)
arr

63

In [ ]:
arr = np.random.randint(10,100, size=(2,3))   #start, stop, dimenension of size
arr

array([[69, 55, 92],
       [69, 83, 93]])

In [ ]:
#Numpy Data type And Type Casting
arr = np.array([1,2,3,4,5])
arr


array([1, 2, 3, 4, 5])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
lst= ["string",1,2,5,6]
arr = np.array(lst)
arr

array(['string', '1', '2', '5', '6'], dtype='<U21')

In [ ]:
arr = np.array([1,2,3.5,4,5])
arr
arr.dtype


dtype('float64')

In [ ]:
arr = np.array([1,2,3,4], dtype = np.float32)
arr
#arr.dtype

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
arr = np.array([1.1,1.2,1.3,3.5], dtype = np.int64)
arr
#arr.dtype


array([1, 1, 1, 3])

In [ ]:
#type casting -> astype()


In [ ]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [ ]:
new_arr = arr.astype(np.float64)
new_arr


array([1., 2., 3.])

In [ ]:
new_arr.dtype

dtype('float64')

In [ ]:
new_arr2 = new_arr.astype(np.int64)
new_arr2


array([1, 2, 3])

In [ ]:
#type casting Error
#we cannot convert integer into float


In [ ]:
arr = np.array([[1,2,3]
               ,[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr.ndim

2

In [ ]:
arr.shape

(2, 3)

In [ ]:
arr.size

6

In [ ]:
arr.itemsize

8

In [ ]:
#Array reshaping -> Reshape, Ravel, flatten


In [ ]:
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [ ]:
reshaped2 = arr.reshape(3,2)
print(reshaped2)

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
#ravel  -> connvert 1D array
ravel = reshaped2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [ ]:
ravel[0]= 100
print(ravel)
print(reshaped2)


[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [ ]:
#flatten -> to 1D array
# -> returns a copy of the array
flat = reshaped2.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [ ]:
flat[0]= 1
flat

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Arithmetic Operations on array

In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(b-a)
print(a/b)
print(a*b)
print(b%a)
print(a**2)


[5 7 9]
[3 3 3]
[0.25 0.4  0.5 ]
[ 4 10 18]
[0 1 0]
[1 4 9]


In [ ]:
#universal function
arr = np.array([1,4,9,16])
#square root -> np.sqrt()
print(np.sqrt(arr))


[1. 2. 3. 4.]


In [ ]:
#exponentioal -> np.exp -> e^x ->integer
print(np.exp([1,2]))


[2.71828183 7.3890561 ]


In [ ]:
#sine function -> np.sine
angles = np.array([0, np.pi, np.pi/2])
print(np.sin(angles))


[0.0000000e+00 1.2246468e-16 1.0000000e+00]


In [ ]:
a = [1,2,3,4,5]
a[-1:-4:-1]
a[:: 2]


[1, 3, 5]

In [ ]:
arr = np.array([10,20,30,40,50])
arr[::2]


array([10, 30, 50])

In [ ]:
#negative Indexing
print(arr[-1])

50


In [4]:
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

In [6]:
print(matrix[0:2:])

[[1 2 3]
 [4 5 6]]


In [8]:
print(matrix[1:, 1:])

[[5 6]
 [8 9]]


In [9]:
#np.take -> built in function to perform indexing and slicing
arr = np.array([10,20,30,40,50])
ind = [0,2]
print(np.take(arr, ind))


[10 30]


In [14]:
#Iterating with nditer()
arr = np.array([[1,2], [3,4]])


In [16]:
for x in np.nditer(arr):
  print(x, end = " ")

1 2 3 4 

In [18]:
#ndenumerate() -> both index + value
for ind, x in np.ndenumerate(arr):
  print(ind,x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [19]:
#view vs Copies
arr = np.array([1,2,3,4,5])
view = arr[1:3]
view

array([2, 3])

In [20]:
view[0] = 200

In [21]:
view

array([200,   3])

In [22]:
#copy
copy = arr[1:3].copy()
copy

array([200,   3])

In [23]:
copy[0] =2
copy

array([2, 3])

In [24]:
arr

array([  1, 200,   3,   4,   5])

In [25]:
#transpose
arr = np.array([[1,2],[3,4]])
arr

array([[1, 2],
       [3, 4]])

In [26]:
print(arr.transpose())

[[1 3]
 [2 4]]


In [28]:
#swapaxes ->swap 2 specific axes in a matrix
arr = np.array([[[1,2],[3,4]]])
arr.shape

(1, 2, 2)

In [30]:
swap = np.swapaxes(arr,0,1)
swap.shape

(2, 1, 2)

In [ ]:
#concatenation

In [37]:
a = np.array([1,2])
b  = np.array([3,4])


In [35]:
combine = np.concatenate((a,b))
combine

array([1, 2, 3, 4])

In [38]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

In [39]:
print(np.vstack((arr1,arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [41]:
print(np.hstack((arr1,arr2)))

[[1 2 5 6]
 [3 4 7 8]]


In [43]:
print(np.stack((arr1,arr2),axis = 0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [44]:
print(np.stack((arr1,arr2),axis = 1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


In [46]:
arr1

array([[1, 2],
       [3, 4]])

In [48]:
print(np.split(arr1,1))

[array([[1, 2],
       [3, 4]])]


In [49]:
print(np.hsplit(arr1,2))

[array([[1],
       [3]]), array([[2],
       [4]])]


In [50]:
#repeating :
arr = np.array([1,2,3])
print(np.repeat(arr,3))


[1 1 1 2 2 2 3 3 3]


In [51]:
#tile -> repeat my whole array
print(np.tile(arr, 2))


[1 2 3 1 2 3]


In [52]:
#Aggreagate function -> to summarize the operations
arr = np.array([1,2,3])
print(np.sum(arr))


6


In [53]:
np.mean(arr)

np.float64(2.0)

In [54]:
np.median(arr)

np.float64(2.0)

In [55]:
np.std(arr)

np.float64(0.816496580927726)

In [56]:
np.var(arr)

np.float64(0.6666666666666666)

In [57]:
np.min(arr)

np.int64(1)

In [58]:
np.max(arr)

np.int64(3)

In [60]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
print(np.sum(matrix, axis=1))

[ 6 15 24]


In [62]:
#cumulative Operations -> running total
arr

array([1, 2, 3])

In [63]:
print(np.cumsum(arr))

[1 3 6]


In [64]:
print(np.cumprod(arr))


[1 2 6]


In [66]:
#condtion Based choice
arr


array([1, 2, 3])

In [68]:
result = np.where(arr <= 2, "low","high")
result

array(['low', 'low', 'high'], dtype='<U4')

In [ ]:
#argwhere: row-column position for 2d array


In [69]:
arr

array([1, 2, 3])

In [72]:
arr = np.array([10,20,30,40,50])

In [73]:
print(np.argwhere(arr>20))

[[2]
 [3]
 [4]]


In [74]:

mask = np.logical_and(arr >15, arr<35)
mask

array([False,  True,  True, False, False])

In [75]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
print(np.argwhere(matrix > 5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


In [77]:
#logical and:
arr = np.array([100,2,3,4,5,6])
arr

array([100,   2,   3,   4,   5,   6])

In [79]:
mask = np.logical_and(arr > 3, arr <6)

In [80]:
arr[mask]

array([4, 5])

In [85]:
#logical or:
mask = np.logical_or(arr < 4, arr >5)
mask

array([ True,  True,  True, False, False,  True])

In [86]:
arr[mask]

array([100,   2,   3,   6])

In [88]:
arr2 = np.array([0,1,5,0,5])
arr2

array([0, 1, 5, 0, 5])

In [ ]:
#Broadcasting

In [93]:
image =  np.array([[200,150],[100,250]])
image.shape


(2, 2)

In [91]:
brightness = image +50
brightness

array([[250, 200],
       [150, 300]])

In [ ]:
#Vectorization :
#np.vectorize() -> convert a regular function to be applied on an array.


In [94]:
def square(x):
  return x*x
vfunc = np.vectorize(square)
arr

array([100,   2,   3,   4,   5,   6])

In [95]:
print(vfunc(arr))

[10000     4     9    16    25    36]


In [96]:
#Dealing with missing values:
#np.nan -> not a number.
a = np.array([1,2,np.nan,4])
a

array([ 1.,  2., nan,  4.])

In [ ]:
#np.inf and -np.inf -> positive and negative infinites

In [ ]:
# np.isnan
# np.isinf
#np.isfinite

#--> these are the function used to detech any null values, infinite value or finite value

In [97]:
print(np.isnan(a))

[False False  True False]


In [104]:
b = np.array([1,np.nan,np.inf, 10.2,40])


In [103]:
#print(np.logical_or(np.isinf(b),np.isnan(b))

In [105]:
print(np.isinf(b))


[False False  True False False]


In [107]:
new_b = np.nan_to_num(b)
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])