<a href="https://colab.research.google.com/github/RutujaBidkar/Certifications/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np


In [4]:
arr = np.array([1,2,3])

In [5]:
#dimensions and shape of an array
arr.ndim

1

In [6]:
arr = np.array(34)
arr.ndim

0

In [12]:
a = np.array([[[[]]]])
a.ndim
a.shape

(1, 1, 1, 0)

In [19]:
range = np.arange(1,10, 2)  #start, stop , step

In [20]:
range

array([1, 3, 5, 7, 9])

In [21]:
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
arr = np.linspace(0,1,10) #start stop, number of values
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [28]:
arr = np.logspace(1,3,2)    #logirithmic sacle array -> 10^1 -> 10^3 ...3points
arr

array([  10., 1000.])

In [29]:
#np.Zeros -> array full of zeros
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [32]:
arr= np.zeros([2,3])
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
arr = np.ones([4,2], dtype= int)
arr


array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [35]:
arr = np.full(10,2)    #create an array full of any value
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [36]:
arr = np.full([2,4],7.1)
arr

array([[7.1, 7.1, 7.1, 7.1],
       [7.1, 7.1, 7.1, 7.1]])

In [39]:
arr = np.empty([2,3]) #uninsitalizated array ->create an array without setting any values
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
arr = np.random.rand(10)
arr

array([0.79156713, 0.46220259, 0.05413551, 0.89685133, 0.48598397,
       0.04762336, 0.03851549, 0.05782836, 0.18155016, 0.64582578])

In [42]:
arr = np.random.rand(2,3)   #-> random floats from standard normal distribution
arr

array([[0.64882474, 0.00670896, 0.74545945],
       [0.46072777, 0.58661947, 0.14305127]])

In [43]:
arr = np.random.randint(10,100)
arr

63

In [44]:
arr = np.random.randint(10,100, size=(2,3))   #start, stop, dimenension of size
arr

array([[69, 55, 92],
       [69, 83, 93]])